name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Examine environment variable
      run: |
        echo "TEST_DIR=$(pwd)"
        echo "GITHUB_ENV=${GITHUB_ENV}"
        echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        echo $PWD
    - name: Test with tox
      run: tox -e py
